spring.application.name=jpa-homework

# application-secret.properties도 같이 읽기
spring.profiles.include=secret  

# Entity 만들면 DB테이블 자동 반영
spring.jpa.hibernate.ddl-auto=update  

# 실행되는 SQL 콘솔에 보여주기
spring.jpa.show-sql=true       

# SQL 보기 좋게 정렬
spring.jpa.properties.hibernate.format_sql=true     